import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemButton from "@mui/material/ListItemButton";
import Divider from "@mui/material/Divider";
import ListItemText from "@mui/material/ListItemText";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import Avatar from "@mui/material/Avatar";

export default function Messages() {
  return (
    <List>
      {messages.map(({ person, message, avatar }, index) => (
        <div key={index + person}>
          <ListItemButton>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={avatar} />
            </ListItemAvatar>
            <ListItemText primary={person} secondary={message} />
          </ListItemButton>
          <Divider />
        </div>
      ))}
    </List>
  );
}

const messages = [
  {
    person: "Utkarsh",
    message: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    avatar: "/static/images/avatar/5.jpg",
  },
  {
    person: "John",
    message: `Do you have a suggestion for a good present for John on his work
      anniversary? I am really confused & would love your thoughts on it.`,
    avatar: "/static/images/avatar/1.jpg",
  },
  {
    person: "Alice",
    message:
      "I am trying out this new BBQ recipe. I think this might be amazing.",
    avatar: "/static/images/avatar/2.jpg",
  },
  {
    person: "Sarah",
    message: "I have the tickets to the ReactConf for this year.",
    avatar: "/static/images/avatar/3.jpg",
  },
  {
    person: "Doctor's Office",
    message:
      "My appointment with the doctor was rescheduled for next Saturday.",
    avatar: "/static/images/avatar/4.jpg",
  },
  {
    person: "Emily",
    message: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    avatar: "/static/images/avatar/5.jpg",
  },
  {
    person: "David",
    message: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    avatar: "/static/images/avatar/1.jpg",
  },
];
